In [34]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [35]:
pd.set_option('display.max_columns', None)

In [36]:
shot_df = pd.read_csv("NBA_2004_2023_Shots.csv")
shot_df.head()

,SEASON_1,SEASON_2,TEAM_ID,TEAM_NAME,PLAYER_ID,PLAYER_NAME,POSITION_GROUP,POSITION,GAME_DATE,GAME_ID,HOME_TEAM,AWAY_TEAM,EVENT_TYPE,SHOT_MADE,ACTION_TYPE,SHOT_TYPE,BASIC_ZONE,ZONE_NAME,ZONE_ABB,ZONE_RANGE,LOC_X,LOC_Y,SHOT_DISTANCE,QUARTER,MINS_LEFT,SECS_LEFT
0,2023,2022-23,1610612764,Washington Wizards,203078,Bradley Beal,G,SG,10-19-2022,22200004,IND,WAS,Made Shot,True,Jump Shot,3PT Field Goal,Left Corner 3,Left Side,L,24+ ft.,23.4,12.95,24,1,11,20
1,2023,2022-23,1610612764,Washington Wizards,204001,Kristaps Porzingis,C,C,10-19-2022,22200004,IND,WAS,Missed Shot,False,Step Back Jump shot,3PT Field Goal,Above the Break 3,Center,C,24+ ft.,-0.4,31.45,26,1,10,52
2,2023,2022-23,1610612764,Washington Wizards,1628420,Monte Morris,G,PG,10-19-2022,22200004,IND,WAS,Made Shot,True,Running Finger Roll Layup Shot,2PT Field Goal,Restricted Area,Center,C,Less Than 8 ft.,-1.3,5.25,1,1,10,39
3,2023,2022-23,1610612764,Washington Wizards,204001,Kristaps Porzingis,C,C,10-19-2022,22200004,IND,WAS,Made Shot,True,Cutting Dunk Shot,2PT Field Goal,Restricted Area,Center,C,Less Than 8 ft.,-0.1,7.25,2,1,10,31
4,2023,2022-23,1610612764,Washington Wizards,1630166,Deni Avdija,F,SF,10-19-2022,22200004,IND,WAS,Made Shot,True,Cutting Dunk Shot,2PT Field Goal,Restricted Area,Center,C,Less Than 8 ft.,1.8,7.15,2,1,10,5

In [37]:
shot_df.shape

(4012561, 26)

In [38]:
shot_df["ACTION_TYPE"].unique()

array(['Jump Shot', 'Step Back Jump shot',
       'Running Finger Roll Layup Shot', 'Cutting Dunk Shot',
       'Driving Layup Shot', 'Pullup Jump shot',
       'Driving Finger Roll Layup Shot', 'Tip Layup Shot',
       'Turnaround Jump Shot', 'Driving Reverse Layup Shot',
       'Running Reverse Layup Shot', 'Layup Shot',
       'Running Pull-Up Jump Shot', 'Dunk Shot', 'Reverse Layup Shot',
       'Running Dunk Shot', 'Floating Jump shot',
       'Driving Floating Jump Shot', 'Cutting Layup Shot',
       'Putback Layup Shot', 'Turnaround Fadeaway shot',
       'Running Jump Shot', 'Turnaround Hook Shot', 'Running Layup Shot',
       'Driving Hook Shot', 'Driving Dunk Shot', 'Fadeaway Jump Shot',
       'Running Alley Oop Dunk Shot',
       'Turnaround Fadeaway Bank Jump Shot',
       'Cutting Finger Roll Layup Shot', 'Running Alley Oop Layup Shot',
       'Tip Dunk Shot', 'Driving Floating Bank Jump Shot',
       'Alley Oop Dunk Shot', 'Putback Dunk Shot', 'Hook Shot',
       'Alley Oop Layup shot', 'Turnaround Bank shot', 'Hook Bank Shot',
       'Jump Bank Shot', 'Driving Bank Hook Shot', 'Fadeaway Bank shot',
       'Reverse Dunk Shot', 'Finger Roll Layup Shot',
       'Turnaround Bank Hook Shot', 'Step Back Bank Jump Shot',
       'Driving Reverse Dunk Shot', 'Running Reverse Dunk Shot',
       'Driving Bank shot', 'Pullup Bank shot', 'Driving Jump shot',
       'No Shot', 'Running Hook Shot', 'Slam Dunk Shot',
       'Running Bank shot', 'Tip Shot', 'Putback Slam Dunk Shot',
       'Jump Hook Shot', 'Running Tip Shot', 'Driving Slam Dunk Shot',
       'Reverse Slam Dunk Shot', 'Running Slam Dunk Shot',
       'Running Bank Hook Shot', 'Jump Bank Hook Shot',
       'Putback Reverse Dunk Shot', 'Driving Finger Roll Shot',
       'Finger Roll Shot', 'Follow Up Dunk Shot',
       'Turnaround Finger Roll Shot', 'Running Finger Roll Shot'],
      dtype=object)

In [39]:
shot_df.columns

Index(['SEASON_1', 'SEASON_2', 'TEAM_ID', 'TEAM_NAME', 'PLAYER_ID',
       'PLAYER_NAME', 'POSITION_GROUP', 'POSITION', 'GAME_DATE', 'GAME_ID',
       'HOME_TEAM', 'AWAY_TEAM', 'EVENT_TYPE', 'SHOT_MADE', 'ACTION_TYPE',
       'SHOT_TYPE', 'BASIC_ZONE', 'ZONE_NAME', 'ZONE_ABB', 'ZONE_RANGE',
       'LOC_X', 'LOC_Y', 'SHOT_DISTANCE', 'QUARTER', 'MINS_LEFT', 'SECS_LEFT'],
      dtype='object')

In [40]:
shot_df.isna().sum()

SEASON_1             0
SEASON_2             0
TEAM_ID              0
TEAM_NAME            0
PLAYER_ID            0
PLAYER_NAME          0
POSITION_GROUP    6666
POSITION          6666
GAME_DATE            0
GAME_ID              0
HOME_TEAM            0
AWAY_TEAM            0
EVENT_TYPE           0
SHOT_MADE            0
ACTION_TYPE          0
SHOT_TYPE            0
BASIC_ZONE           0
ZONE_NAME            0
ZONE_ABB             0
ZONE_RANGE           0
LOC_X                0
LOC_Y                0
SHOT_DISTANCE        0
QUARTER              0
MINS_LEFT            0
SECS_LEFT            0
dtype: int64

In [41]:
# players that do not have a position/position group
positionless_players = shot_df[shot_df["POSITION"].isna()]["PLAYER_NAME"].unique()

In [42]:
# sanity check: no positionless players have position ever recorded
shot_df[shot_df["PLAYER_NAME"].isin(positionless_players)]["POSITION"].sum()

0

In [43]:
positionless_players

array(['O.G. Anunoby', 'Jeff Dowtin Jr.', 'John Butler Jr.',
       'Chance Comanche', 'AJ Green', 'Xavier Tillman',
       'Xavier Tillman Sr.', 'OG Anunoby', 'Jeff Dowtin',
       'Charlie Brown Jr.', 'M.J. Walker', 'Trevon Scott', 'P.J. Dozier',
       'Cam Reynolds', 'T.J. Leaf', 'Michael Frazier II',
       'Jeffery Taylor', 'Vitor Faverani'], dtype=object)

In [44]:
shot_df["TEAM_ID"].astype("object")
shot_df["PLAYER_ID"].astype("object")
shot_df["GAME_ID"].astype("object")
# shot_df["SEASON_1"] = pd.to_datetime(shot_df["SEASON_1"], format="%Y")
shot_df["GAME_DATE"] = pd.to_datetime(shot_df["GAME_DATE"])
shot_df.dtypes

SEASON_1                   int64
SEASON_2                  object
TEAM_ID                    int64
TEAM_NAME                 object
PLAYER_ID                  int64
PLAYER_NAME               object
POSITION_GROUP            object
POSITION                  object
GAME_DATE         datetime64[ns]
GAME_ID                    int64
HOME_TEAM                 object
AWAY_TEAM                 object
EVENT_TYPE                object
SHOT_MADE                   bool
ACTION_TYPE               object
SHOT_TYPE                 object
BASIC_ZONE                object
ZONE_NAME                 object
ZONE_ABB                  object
ZONE_RANGE                object
LOC_X                    float64
LOC_Y                    float64
SHOT_DISTANCE              int64
QUARTER                    int64
MINS_LEFT                  int64
SECS_LEFT                  int64
dtype: object

In [45]:
shot_df.head()

,SEASON_1,SEASON_2,TEAM_ID,TEAM_NAME,PLAYER_ID,PLAYER_NAME,POSITION_GROUP,POSITION,GAME_DATE,GAME_ID,HOME_TEAM,AWAY_TEAM,EVENT_TYPE,SHOT_MADE,ACTION_TYPE,SHOT_TYPE,BASIC_ZONE,ZONE_NAME,ZONE_ABB,ZONE_RANGE,LOC_X,LOC_Y,SHOT_DISTANCE,QUARTER,MINS_LEFT,SECS_LEFT
0,2023,2022-23,1610612764,Washington Wizards,203078,Bradley Beal,G,SG,2022-10-19,22200004,IND,WAS,Made Shot,True,Jump Shot,3PT Field Goal,Left Corner 3,Left Side,L,24+ ft.,23.4,12.95,24,1,11,20
1,2023,2022-23,1610612764,Washington Wizards,204001,Kristaps Porzingis,C,C,2022-10-19,22200004,IND,WAS,Missed Shot,False,Step Back Jump shot,3PT Field Goal,Above the Break 3,Center,C,24+ ft.,-0.4,31.45,26,1,10,52
2,2023,2022-23,1610612764,Washington Wizards,1628420,Monte Morris,G,PG,2022-10-19,22200004,IND,WAS,Made Shot,True,Running Finger Roll Layup Shot,2PT Field Goal,Restricted Area,Center,C,Less Than 8 ft.,-1.3,5.25,1,1,10,39
3,2023,2022-23,1610612764,Washington Wizards,204001,Kristaps Porzingis,C,C,2022-10-19,22200004,IND,WAS,Made Shot,True,Cutting Dunk Shot,2PT Field Goal,Restricted Area,Center,C,Less Than 8 ft.,-0.1,7.25,2,1,10,31
4,2023,2022-23,1610612764,Washington Wizards,1630166,Deni Avdija,F,SF,2022-10-19,22200004,IND,WAS,Made Shot,True,Cutting Dunk Shot,2PT Field Goal,Restricted Area,Center,C,Less Than 8 ft.,1.8,7.15,2,1,10,5

In [46]:
#categorical
shot_df.describe(include=["object", "bool"])

,SEASON_2,TEAM_NAME,PLAYER_NAME,POSITION_GROUP,POSITION,HOME_TEAM,AWAY_TEAM,EVENT_TYPE,SHOT_MADE,ACTION_TYPE,SHOT_TYPE,BASIC_ZONE,ZONE_NAME,ZONE_ABB,ZONE_RANGE
count,4012561,4012561,4012561,4005895,4005895,4012561,4012561,4012561,4012561,4012561,4012561,4012561,4012561,4012561,4012561
unique,20,36,2058,3,17,34,34,2,2,70,2,7,6,6,5
top,2018-19,Golden State Warriors,LeBron James,G,SG,PHX,PHX,Missed Shot,False,Jump Shot,2PT Field Goal,Restricted Area,Center,C,Less Than 8 ft.
freq,219458,137600,28042,1813888,935548,138132,137487,2179750,2179750,1939362,2892717,1279336,2169865,2169865,1648220

In [47]:
#numeric
shot_df.describe()

,SEASON_1,TEAM_ID,PLAYER_ID,GAME_DATE,GAME_ID,LOC_X,LOC_Y,SHOT_DISTANCE,QUARTER,MINS_LEFT,SECS_LEFT
count,4.012561e+06,4.012561e+06,4.012561e+06,4012561,4.012561e+06,4.012561e+06,4.012561e+06,4.012561e+06,4.012561e+06,4.012561e+06,4.012561e+06
mean,2.013656e+03,1.610613e+09,3.659406e+05,2013-09-19 08:56:04.384590080,2.126623e+07,9.077217e-02,1.226589e+01,1.250812e+01,2.480542e+00,5.337424e+00,2.876627e+01
min,2.004000e+03,1.610613e+09,1.500000e+01,2003-10-28 00:00:00,2.030000e+07,-2.500000e+01,5.000000e-02,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
25%,2.009000e+03,1.610613e+09,2.436000e+03,2008-11-18 00:00:00,2.080016e+07,-2.800000e+00,5.855000e+00,2.000000e+00,1.000000e+00,2.000000e+00,1.400000e+01
50%,2.014000e+03,1.610613e+09,2.011880e+05,2013-12-21 00:00:00,2.130040e+07,0.000000e+00,7.935000e+00,1.300000e+01,2.000000e+00,5.000000e+00,2.900000e+01
75%,2.019000e+03,1.610613e+09,2.034580e+05,2018-11-08 00:00:00,2.180016e+07,2.800000e+00,1.845000e+01,2.300000e+01,3.000000e+00,8.000000e+00,4.400000e+01
max,2.023000e+03,1.610613e+09,1.641645e+06,2023-04-09 00:00:00,2.220123e+07,2.500000e+01,9.365000e+01,8.900000e+01,8.000000e+00,1.200000e+01,5.900000e+01
std,5.778994e+00,8.635580e+00,5.784671e+05,NaN,5.778948e+05,1.019809e+01,8.485120e+00,1.009542e+01,1.137880e+00,3.463645e+00,1.745254e+01

In [48]:
shot_df["BASIC_ZONE"].unique()

array(['Left Corner 3', 'Above the Break 3', 'Restricted Area',
       'Mid-Range', 'In The Paint (Non-RA)', 'Right Corner 3',
       'Backcourt'], dtype=object)

In [49]:
shot_df["ZONE_NAME"].unique()

array(['Left Side', 'Center', 'Left Side Center', 'Right Side Center',
       'Right Side', 'Back Court'], dtype=object)

In [50]:
shot_df["TIME_LEFT_QUARTER"] = shot_df["MINS_LEFT"] * 60 + shot_df["SECS_LEFT"]
shot_df["TIME_LEFT_GAME"] = (4 - shot_df["QUARTER"]) * 15 * 60 + shot_df["TIME_LEFT_QUARTER"]

In [56]:
shot_df["SHOT_VALUE"] = shot_df["SHOT_MADE"].astype(int) * shot_df["SHOT_TYPE"].str[:1].astype(int)